#bridge-file-version: #52
HIDDEN 
execute @a ~ ~ ~ detect ~ ~ ~ ancient_debris -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ barrel -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ barrier -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ basalt -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ beacon -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ bedrock -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ bee_nest -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ beehive -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ black_glazed_terracotta -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ blackstone -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ blast_furnace -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ blue_glazed_terracotta -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ blue_ice -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ bone_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ bookshelf -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ brick_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ brown_glazed_terracotta -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ brown_mushroom_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ cartography_table -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ carved_pumpkin -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ chain_command_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ chemical_heat -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ chemistry_table -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ chiseled_nether_bricks -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ chiseled_polished_blackstone -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ clay -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ coal_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ coal_ore -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ cobblestone -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ command_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ concrete -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ concretePowder -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ coral_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ cracked_nether_bricks -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ cracked_polished_blackstone_bricks -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ crafting_table -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ crimson_hyphae -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ crimson_nylium -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ crimson_planks -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ crying_obsidian -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ cyan_glazed_terracotta -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ diamond_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ diamond_ore -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ dirt -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ dispenser -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ dried_kelp_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ emerald_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ emerald_ore -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ end_bricks -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ end_stone -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ fletching_table -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ frosted_ice -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ furnace -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ gilded_blackstone -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ glowingobsidian -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ glowstone -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ gold_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ gold_ore -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ gray_glazed_terracotta -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ green_glazed_terracotta -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ hardened_clay -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ hay_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ honeycomb_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ ice -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ iron_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ iron_ore -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ jigsaw -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ jukebox -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ lapis_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ lapis_ore -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ light_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ light_blue_glazed_terracotta -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ lime_glazed_terracotta -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ lit_blast_furnace -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ lit_furnace -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ lit_pumpkin -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ lit_redstone_lamp -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ lit_redstone_ore -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ lit_smoker -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ lodestone -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ log -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ log2 -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ loom -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ magenta_glazed_terracotta -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ magma -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ melon_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ mob_spawner -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ monster_egg -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ mossy_cobblestone -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ movingBlock -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ mycelium -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ nether_brick -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ nether_gold_ore -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ nether_wart -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ nether_wart_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ netherite_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ netherreactor -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ noteblock -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ observer -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ orange_glazed_terracotta -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ packed_ice -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ pink_glazed_terracotta -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ planks -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ podzol -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ polished_basalt -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ polished_blackstone -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ polished_blackstone_bricks -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ prismarine -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ pumpkin -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ pumpkin_stem -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ purple_glazed_terracotta -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ purpur_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ quartz_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ quartz_bricks -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ quartz_ore -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ red_glazed_terracotta -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ red_mushroom_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ red_nether_brick -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ red_sandstone -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ redstone_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ redstone_lamp -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ repeating_command_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ reserved6 -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ respawn_anchor -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ sandstone -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ seaLantern -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ shroomlight -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ shulker_box -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ silver_glazed_terracotta -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ smithing_table -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ smoker -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ smooth_stone -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ soul_sand -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ soul_soil -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ sponge -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ stained_hardened_clay -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ stone -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ stonebrick -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ stripped_acacia_log -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ stripped_birch_log -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ stripped_crimson_hyphae -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ stripped_crimson_stem -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ stripped_dark_oak_log -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ stripped_jungle_log -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ stripped_oak_log -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ stripped_spruce_log -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ structure_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ target -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ tnt -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ undyed_shulker_box -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ warped_planks -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ warped_wart_block -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ white_glazed_terracotta -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ wood -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ wool -1 scoreboard players add @s phase 1
execute @a ~ ~ ~ detect ~ ~ ~ yellow_glazed_terracotta -1 scoreboard players add @s phase 1
execute @a[scores={phase=3..}] ~ ~ ~ tellraw @a[tag=notify] {"rawtext":[{"text":"§4Hydra §r> §c"},{"selector":"@s"},{"text":" Attempted Phase [Lvl. "},{"score":{"name":"@s","objective":"phase"}},{"text":"]"}]}
execute @a[scores={phase=1..}] ~ ~ ~ tp ~ ~1 ~
 
execute @a[scores={phase=1..}] ~ ~ ~ detect ~ ~ ~ air -1 scoreboard players remove @s phase 1
 
execute @a[scores={phase=50..}] ~ ~ ~ tag @s add hban