replaceitem entity @s slot.enderchest 0 air 0
replaceitem entity @s slot.enderchest 1 air 0
replaceitem entity @s slot.enderchest 2 air 0
replaceitem entity @s slot.enderchest 3 air 0
replaceitem entity @s slot.enderchest 4 air 0
replaceitem entity @s slot.enderchest 5 air 0
replaceitem entity @s slot.enderchest 6 air 0
replaceitem entity @s slot.enderchest 7 air 0
replaceitem entity @s slot.enderchest 8 air 0
replaceitem entity @s slot.enderchest 9 air 0
replaceitem entity @s slot.enderchest 10 air 0
replaceitem entity @s slot.enderchest 11 air 0
replaceitem entity @s slot.enderchest 12 air 0
replaceitem entity @s slot.enderchest 13 air 0
replaceitem entity @s slot.enderchest 14 air 0
replaceitem entity @s slot.enderchest 15 air 0
replaceitem entity @s slot.enderchest 16 air 0
replaceitem entity @s slot.enderchest 17 air 0
replaceitem entity @s slot.enderchest 18 air 0
replaceitem entity @s slot.enderchest 19 air 0
replaceitem entity @s slot.enderchest 20 air 0
replaceitem entity @s slot.enderchest 21 air 0
replaceitem entity @s slot.enderchest 22 air 0
replaceitem entity @s slot.enderchest 23 air 0
replaceitem entity @s slot.enderchest 24 air 0
replaceitem entity @s slot.enderchest 25 air 0
replaceitem entity @s slot.enderchest 26 air 0
execute @s ~~~ tell @a[tag=staff] §cusers inventory chest was wiped by admin