#bridge-file-version: #8
HIDDEN 
clear @s acacia_button
clear @s acacia_door
clear @s acacia_fence_gate
clear @s acacia_pressure_plate
clear @s acacia_stairs
clear @s acacia_standing_sign
clear @s acacia_trapdoor
clear @s acacia_wall_sign
clear @s activator_rail
clear @s ancient_debris
clear @s andesite_stairs
clear @s anvil
clear @s bamboo
clear @s bamboo_sapling
clear @s barrel
clear @s barrier
clear @s basalt
clear @s beacon
clear @s bed
clear @s bedrock
clear @s bee_nest
clear @s beehive
clear @s beetroot
clear @s bell
clear @s birch_button
clear @s birch_door
clear @s birch_fence_gate
clear @s birch_pressure_plate
clear @s birch_stairs
clear @s birch_standing_sign
clear @s birch_trapdoor
clear @s birch_wall_sign
clear @s black_glazed_terracotta
clear @s blackstone
clear @s blackstone_double_slab
clear @s blackstone_slab
clear @s blackstone_stairs
clear @s blackstone_wall
clear @s blast_furnace
clear @s blue_glazed_terracotta
clear @s blue_ice
clear @s bone_block
clear @s bookshelf
clear @s border_block
clear @s brewing_stand
clear @s brick_block
clear @s brick_stairs
clear @s brown_glazed_terracotta
clear @s brown_mushroom
clear @s brown_mushroom_block
clear @s bubble_column
clear @s cactus
clear @s cake
clear @s camera
clear @s campfire
clear @s carpet
clear @s carrots
clear @s cartography_table
clear @s carved_pumpkin
clear @s cauldron
clear @s chain
clear @s chain_command_block
clear @s chemical_heat
clear @s chemistry_table
clear @s chest
clear @s chiseled_nether_bricks
clear @s chiseled_polished_blackstone
clear @s chorus_flower
clear @s chorus_plant
clear @s clay
clear @s coal_block
clear @s coal_ore
clear @s cobblestone
clear @s cobblestone_wall
clear @s cocoa
clear @s command_block
clear @s composter
clear @s concrete
clear @s concretePowder
clear @s conduit
clear @s coral
clear @s coral_block
clear @s coral_fan
clear @s coral_fan_dead
clear @s coral_fan_hang
clear @s coral_fan_hang2
clear @s coral_fan_hang3
clear @s cracked_nether_bricks
clear @s cracked_polished_blackstone_bricks
clear @s crafting_table
clear @s crimson_button
clear @s crimson_door
clear @s crimson_double_slab
clear @s crimson_fence
clear @s crimson_fence_gate
clear @s crimson_fungus
clear @s crimson_hyphae
clear @s crimson_nylium
clear @s crimson_planks
clear @s crimson_pressure_plate
clear @s crimson_roots
clear @s crimson_slab
clear @s crimson_stairs
clear @s crimson_standing_sign
clear @s crimson_stem
clear @s crimson_trapdoor
clear @s crimson_wall_sign
clear @s crying_obsidian
clear @s cyan_glazed_terracotta
clear @s dark_oak_button
clear @s dark_oak_door
clear @s dark_oak_fence_gate
clear @s dark_oak_pressure_plate
clear @s dark_oak_stairs
clear @s dark_oak_trapdoor
clear @s dark_prismarine_stairs
clear @s darkoak_standing_sign
clear @s darkoak_wall_sign
clear @s daylight_detector
clear @s daylight_detector_inverted
clear @s deadbush
clear @s detector_rail
clear @s diamond_block
clear @s diamond_ore
clear @s diorite_stairs
clear @s dirt
clear @s dispenser
clear @s double_plant
clear @s double_stone_slab
clear @s double_stone_slab2
clear @s double_stone_slab3
clear @s double_stone_slab4
clear @s double_wooden_slab
clear @s dragon_egg
clear @s dried_kelp_block
clear @s dropper
clear @s emerald_block
clear @s emerald_ore
clear @s enchanting_table
clear @s end_brick_stairs
clear @s end_bricks
clear @s end_gateway
clear @s end_portal
clear @s end_portal_frame
clear @s end_rod
clear @s end_stone
clear @s ender_chest
clear @s farmland
clear @s fence
clear @s fence_gate
clear @s fire
clear @s fletching_table
clear @s flower_pot
clear @s flowing_lava
clear @s flowing_water
clear @s frame
clear @s frosted_ice
clear @s furnace
clear @s gilded_blackstone
clear @s glass
clear @s glass_pane
clear @s glowingobsidian
clear @s glowstone
clear @s gold_block
clear @s gold_ore
clear @s golden_rail
clear @s granite_stairs
clear @s grass
clear @s grass_path
clear @s gravel
clear @s gray_glazed_terracotta
clear @s green_glazed_terracotta
clear @s grindstone
clear @s hardened_clay
clear @s hay_block
clear @s heavy_weighted_pressure_plate
clear @s honey_block
clear @s honeycomb_block
clear @s hopper
clear @s ice
clear @s iron_bars
clear @s iron_block
clear @s iron_door
clear @s iron_ore
clear @s iron_trapdoor
clear @s jigsaw
clear @s jukebox
clear @s jungle_button
clear @s jungle_door
clear @s jungle_fence_gate
clear @s jungle_pressure_plate
clear @s jungle_stairs
clear @s jungle_standing_sign
clear @s jungle_trapdoor
clear @s jungle_wall_sign
clear @s kelp
clear @s ladder
clear @s lantern
clear @s lapis_block
clear @s lapis_ore
clear @s lava
clear @s lava_cauldron
clear @s leaves
clear @s leaves2
clear @s lectern
clear @s lever
clear @s light_block
clear @s light_blue_glazed_terracotta
clear @s light_weighted_pressure_plate
clear @s lime_glazed_terracotta
clear @s lit_blast_furnace
clear @s lit_furnace
clear @s lit_pumpkin
clear @s lit_redstone_lamp
clear @s lit_redstone_ore
clear @s lit_smoker
clear @s lodestone
clear @s log
clear @s log2
clear @s loom
clear @s magenta_glazed_terracotta
clear @s magma
clear @s melon_block
clear @s melon_stem
clear @s mob_spawner
clear @s monster_egg
clear @s mossy_cobblestone
clear @s mossy_cobblestone_stairs
clear @s mossy_stone_brick_stairs
clear @s movingBlock
clear @s mycelium
clear @s nether_brick
clear @s nether_brick_fence
clear @s nether_brick_stairs
clear @s nether_gold_ore
clear @s nether_sprouts
clear @s nether_wart
clear @s nether_wart_block
clear @s netherite_block
clear @s netherrack
clear @s netherreactor
clear @s normal_stone_stairs
clear @s noteblock
clear @s oak_stairs
clear @s observer
clear @s obsidian
clear @s orange_glazed_terracotta
clear @s packed_ice
clear @s pink_glazed_terracotta
clear @s piston
clear @s pistonArmCollision
clear @s planks
clear @s podzol
clear @s polished_andesite_stairs
clear @s polished_basalt
clear @s polished_blackstone
clear @s polished_blackstone_brick_double_slab
clear @s polished_blackstone_brick_slab
clear @s polished_blackstone_brick_stairs
clear @s polished_blackstone_brick_wall
clear @s polished_blackstone_bricks
clear @s polished_blackstone_button
clear @s polished_blackstone_double_slab
clear @s polished_blackstone_pressure_plate
clear @s polished_blackstone_slab
clear @s polished_blackstone_stairs
clear @s polished_blackstone_wall
clear @s polished_diorite_stairs
clear @s polished_granite_stairs
clear @s portal
clear @s potatoes
clear @s powered_comparator
clear @s powered_repeater
clear @s prismarine
clear @s prismarine_bricks_stairs
clear @s prismarine_stairs
clear @s pumpkin
clear @s pumpkin_stem
clear @s purple_glazed_terracotta
clear @s purpur_block
clear @s purpur_stairs
clear @s quartz_block
clear @s quartz_bricks
clear @s quartz_ore
clear @s quartz_stairs
clear @s rail
clear @s red_flower
clear @s red_glazed_terracotta
clear @s red_mushroom
clear @s red_mushroom_block
clear @s red_nether_brick
clear @s red_nether_brick_stairs
clear @s red_sandstone
clear @s red_sandstone_stairs
clear @s redstone_block
clear @s redstone_lamp
clear @s redstone_ore
clear @s redstone_torch
clear @s redstone_wire
clear @s reeds
clear @s repeating_command_block
clear @s reserved6
clear @s respawn_anchor
clear @s sand
clear @s sandstone
clear @s sandstone_stairs
clear @s sapling
clear @s scaffolding
clear @s seaLantern
clear @s sea_pickle
clear @s seagrass
clear @s shroomlight
clear @s shulker_box
clear @s silver_glazed_terracotta
clear @s skull
clear @s slime
clear @s smithing_table
clear @s smoker
clear @s smooth_quartz_stairs
clear @s smooth_red_sandstone_stairs
clear @s smooth_sandstone_stairs
clear @s smooth_stone
clear @s snow
clear @s snow_layer
clear @s soul_campfire
clear @s soul_fire
clear @s soul_lantern
clear @s soul_sand
clear @s soul_soil
clear @s soul_torch
clear @s sponge
clear @s spruce_button
clear @s spruce_door
clear @s spruce_fence_gate
clear @s spruce_pressure_plate
clear @s spruce_stairs
clear @s spruce_standing_sign
clear @s spruce_trapdoor
clear @s spruce_wall_sign
clear @s stained_glass
clear @s stained_glass_pane
clear @s stained_hardened_clay
clear @s standing_banner
clear @s standing_sign
clear @s stickyPistonArmCollision
clear @s sticky_piston
clear @s stone
clear @s stone_brick_stairs
clear @s stone_button
clear @s stone_pressure_plate
clear @s stone_slab
clear @s stone_slab2
clear @s stone_slab3
clear @s stone_slab4
clear @s stone_stairs
clear @s stonebrick
clear @s stonecutter
clear @s stonecutter_block
clear @s stripped_acacia_log
clear @s stripped_birch_log
clear @s stripped_crimson_hyphae
clear @s stripped_crimson_stem
clear @s stripped_dark_oak_log
clear @s stripped_jungle_log
clear @s stripped_oak_log
clear @s stripped_spruce_log
clear @s stripped_warped_hyphae
clear @s stripped_warped_stem
clear @s structure_block
clear @s structure_void
clear @s sweet_berry_bush
clear @s tallgrass
clear @s target
clear @s tnt
clear @s torch
clear @s trapdoor
clear @s trapped_chest
clear @s tripWire
clear @s tripwire_hook
clear @s turtle_egg
clear @s twisting_vines
clear @s underwater_torch
clear @s undyed_shulker_box
clear @s unlit_redstone_torch
clear @s unpowered_comparator
clear @s unpowered_repeater
clear @s vine
clear @s wall_banner
clear @s wall_sign
clear @s warped_button
clear @s warped_door
clear @s warped_double_slab
clear @s warped_fence
clear @s warped_fence_gate
clear @s warped_fungus
clear @s warped_hyphae
clear @s warped_nylium
clear @s warped_planks
clear @s warped_pressure_plate
clear @s warped_roots
clear @s warped_slab
clear @s warped_stairs
clear @s warped_standing_sign
clear @s warped_stem
clear @s warped_trapdoor
clear @s warped_wall_sign
clear @s warped_wart_block
clear @s water
clear @s waterlily
clear @s web
clear @s weeping_vines
clear @s wheat
clear @s white_glazed_terracotta
clear @s wither_rose
clear @s wood
clear @s wooden_button
clear @s wooden_door
clear @s wooden_pressure_plate
clear @s wooden_slab
clear @s wool
clear @s yellow_flower
clear @s yellow_glazed_terracotta