#bridge-file-version: #0
HIDDEN 
#credit: *๖̶̶̶ζ͜͡𝑵𝒊𝒈𝒉𝒕𝒘𝒂𝒍𝒌𝒆𝒓𝑳𝒐𝒕𝒔꧂#2877 (NightwalkerLots)
clear @s spawn_egg
clear @s bat_spawn_egg
clear @s bee_spawn_egg
clear @s blaze_spawn_egg
clear @s cat_spawn_egg
clear @s cave_spider_spawn_egg
clear @s chicken_spawn_egg
clear @s cod_spawn_egg
clear @s cow_spawn_egg
clear @s creeper_spawn_egg
clear @s dolphin_spawn_egg
clear @s donkey_spawn_egg
clear @s drowned_spawn_egg
clear @s elder_guardian_spawn_egg
clear @s enderman_spawn_egg
clear @s endermite_spawn_egg
clear @s evoker_spawn_egg
clear @s fox_spawn_egg
clear @s ghast_spawn_egg
clear @s guardian_spawn_egg
clear @s hoglin_spawn_egg
clear @s horse_spawn_egg
clear @s husk_spawn_egg
clear @s llama_spawn_egg
clear @s magma_cube_spawn_egg
clear @s mooshroom_spawn_egg
clear @s mule_spawn_egg
clear @s npc_spawn_egg
clear @s ocelot_spawn_egg
clear @s panda_spawn_egg
clear @s parrot_spawn_egg
clear @s phantom_spawn_egg
clear @s pig_spawn_egg
clear @s piglin_brute_spawn_egg
clear @s piglin_spawn_egg
clear @s pillager_spawn_egg
clear @s polar_bear_spawn_egg
clear @s pufferfish_spawn_egg
clear @s rabbit_spawn_egg
clear @s ravager_spawn_egg
clear @s salmon_spawn_egg
clear @s sheep_spawn_egg
clear @s shulker_spawn_egg
clear @s silverfish_spawn_egg
clear @s skeleton_horse_spawn_egg
clear @s skeleton_spawn_egg
clear @s slime_spawn_egg
clear @s spider_spawn_egg
clear @s squid_spawn_egg
clear @s stray_spawn_egg
clear @s strider_spawn_egg
clear @s tropical_fish_spawn_egg
clear @s turtle_spawn_egg
clear @s vex_spawn_egg
clear @s vindicator_spawn_egg
clear @s villager_spawn_egg
clear @s wandering_trader_spawn_egg
clear @s witch_spawn_egg
clear @s wither_skeleton_spawn_egg
clear @s wolf_spawn_egg
clear @s zoglin_spawn_egg
clear @s zombie_horse_spawn_egg
clear @s zombie_pigman_spawn_egg
clear @s zombie_spawn_egg
clear @s zombie_villager_spawn_egg
