HIDDEN 
clear @s spawn_egg 0
clear @s spawn_egg 1
clear @s spawn_egg 2
clear @s spawn_egg 3
clear @s spawn_egg 4
clear @s spawn_egg 5
clear @s spawn_egg 6
clear @s spawn_egg 7
clear @s spawn_egg 8
clear @s spawn_egg 9
clear @s spawn_egg 10
clear @s spawn_egg 11
clear @s spawn_egg 12
clear @s spawn_egg 13
clear @s spawn_egg 14
clear @s spawn_egg 15
clear @s spawn_egg 16
clear @s spawn_egg 17
clear @s spawn_egg 18
clear @s spawn_egg 19
clear @s spawn_egg 20
clear @s spawn_egg 21
clear @s spawn_egg 22
clear @s spawn_egg 23
clear @s spawn_egg 24
clear @s spawn_egg 25
clear @s spawn_egg 26
clear @s spawn_egg 27
clear @s spawn_egg 28
clear @s spawn_egg 29
clear @s spawn_egg 30
clear @s spawn_egg 31
clear @s spawn_egg 30
clear @s spawn_egg 40
clear @s spawn_egg 44
clear @s spawn_egg 42
clear @s spawn_egg 43
clear @s spawn_egg 44
clear @s spawn_egg 45
clear @s spawn_egg 46
clear @s spawn_egg 47
clear @s spawn_egg 48
clear @s spawn_egg 49
clear @s spawn_egg 50
clear @s spawn_egg 55
clear @s spawn_egg 52
clear @s spawn_egg 53
clear @s spawn_egg 54
clear @s spawn_egg 55
clear @s spawn_egg 56
clear @s spawn_egg 57
clear @s spawn_egg 58
clear @s spawn_egg 59
clear @s spawn_egg 60
clear @s spawn_egg 66
clear @s spawn_egg 62
clear @s spawn_egg 63
clear @s spawn_egg 64
clear @s spawn_egg 65
clear @s spawn_egg 66
clear @s spawn_egg 67
clear @s spawn_egg 68
clear @s spawn_egg 69
