#bridge-file-version: #0
HIDDEN 
#credit: *๖̶̶̶ζ͜͡𝑵𝒊𝒈𝒉𝒕𝒘𝒂𝒍𝒌𝒆𝒓𝑳𝒐𝒕𝒔꧂#2877 (NightwalkerLots)
clear @a spawn_egg
clear @a bat_spawn_egg
clear @a bee_spawn_egg
clear @a blaze_spawn_egg
clear @a cat_spawn_egg
clear @a cave_spider_spawn_egg
clear @a chicken_spawn_egg
clear @a cod_spawn_egg
clear @a cow_spawn_egg
clear @a creeper_spawn_egg
clear @a dolphin_spawn_egg
clear @a donkey_spawn_egg
clear @a drowned_spawn_egg
clear @a elder_guardian_spawn_egg
clear @a enderman_spawn_egg
clear @a endermite_spawn_egg
clear @a evoker_spawn_egg
clear @a fox_spawn_egg
clear @a ghast_spawn_egg
clear @a guardian_spawn_egg
clear @a hoglin_spawn_egg
clear @a horse_spawn_egg
clear @a husk_spawn_egg
clear @a llama_spawn_egg
clear @a magma_cube_spawn_egg
clear @a mooshroom_spawn_egg
clear @a mule_spawn_egg
clear @a npc_spawn_egg
clear @a ocelot_spawn_egg
clear @a panda_spawn_egg
clear @a parrot_spawn_egg
clear @a phantom_spawn_egg
clear @a pig_spawn_egg
clear @a piglin_brute_spawn_egg
clear @a piglin_spawn_egg
clear @a pillager_spawn_egg
clear @a polar_bear_spawn_egg
clear @a pufferfish_spawn_egg
clear @a rabbit_spawn_egg
clear @a ravager_spawn_egg
clear @a salmon_spawn_egg
clear @a sheep_spawn_egg
clear @a shulker_spawn_egg
clear @a silverfish_spawn_egg
clear @a skeleton_horse_spawn_egg
clear @a skeleton_spawn_egg
clear @a slime_spawn_egg
clear @a spider_spawn_egg
clear @a squid_spawn_egg
clear @a stray_spawn_egg
clear @a strider_spawn_egg
clear @a tropical_fish_spawn_egg
clear @a turtle_spawn_egg
clear @a vex_spawn_egg
clear @a vindicator_spawn_egg
clear @a villager_spawn_egg
clear @a wandering_trader_spawn_egg
clear @a witch_spawn_egg
clear @a wither_skeleton_spawn_egg
clear @a wolf_spawn_egg
clear @a zoglin_spawn_egg
clear @a zombie_horse_spawn_egg
clear @a zombie_pigman_spawn_egg
clear @a zombie_spawn_egg
clear @a zombie_villager_spawn_egg